spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/spring?serverTimezone=GMT&characterEncoding=utf8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize:
    minIdle:
    maxActive:
    maxWait:
